contributor profil component
WildCodeSchool/2022-03-JS-RemoteFR-Outsiders-P3-SocialTeamConsulting pull request #31
Opened 2022-06-15 08:02 UTC by froustex

2022-06-15 12:05 UTC, sebastienpuigrenier requested changes

2022-06-15 12:05 UTC, sebastienpuigrenier commented on frontend/src/components/ProfilInterv.jsx
> +          <p>Nom Prénom</p>
Nom et prénom doivent être dans 2 champs pour être en adéquation avec la base de donnée

2022-06-15 12:05 UTC, sebastienpuigrenier commented on frontend/src/components/ProfilInterv.jsx
> +        <label htmlFor="address">
l'adresse doit être découpé comme dans la bdd :
adresse
code postale
ville

2022-06-15 12:05 UTC, sebastienpuigrenier commented on frontend/src/style/ProfilInterv.css
> +label {
donner une classe ou intégrer le lbal dans le profil pour éviter les pb de css

2022-06-15 12:05 UTC, sebastienpuigrenier commented on frontend/src/style/ProfilInterv.css
> +.button-blue {
button-blue est déjà dans le css global et ne devrait pas être redéfini dans ce css

2022-06-17 08:26 UTC, kpeset approved these changes

2022-06-17 08:26 UTC, kpeset reviewed
C'est en attente ?

2022-06-17 09:58 UTC, sebastienpuigrenier approved these changes

2022-06-17 09:59 UTC, Crab-Prog approved these changes

2022-06-17 09:59 UTC, merged