Us user info context
WildCodeSchool/2022-03-JS-RemoteFR-Outsiders-P3-SocialTeamConsulting pull request #51
Opened 2022-06-22 12:36 UTC by kpeset

Mon npm run fix a parfois ajouté des espaces dans d'autres fichiers. Est-ce grave ?

2022-06-22 15:50 UTC, bebaile commented on frontend/src/components/NavBarForm.jsx
> +import ExportContext from "../contexts/Context";
juste pour faire une remarque ;) je dirais que le nom ExportContext n'est pas forcément très approprié. Par définition, un contexte c'est pour rendre dispo des données à tous les composants qui en auraient besoin, donc export n'a pas beaucoup de sens  ! 

Mais ce n'est qu'une remarque de forme.

2022-06-22 15:52 UTC, bebaile approved these changes
C'est bon pour moi

2022-06-22 19:25 UTC, sebastienpuigrenier requested changes

2022-06-22 19:25 UTC, sebastienpuigrenier commented on frontend/src/components/NavBarForm.jsx
> +    console.warn(infoUser);
console.warn a enlever

2022-06-23 12:19 UTC, sebastienpuigrenier approved these changes

2022-06-23 12:19 UTC, merged