Us change inter
WildCodeSchool/2022-03-JS-RemoteFR-Outsiders-P3-SocialTeamConsulting pull request #79
Opened 2022-07-07 17:57 UTC by Crab-Prog

2022-07-07 19:07 UTC, sebastienpuigrenier requested changes

2022-07-08 07:26 UTC, Crab-Prog commented on backend/src/controllers/AccepteController.js
> +          res.status(404).send("Le statut de la mission a change");
done

2022-07-08 07:26 UTC, Crab-Prog commented on frontend/src/App.jsx
> +            path="/back_office/modification_mission_intervenant"
done

2022-07-08 07:28 UTC, sebastienpuigrenier approved these changes

2022-07-08 07:33 UTC, merged